spring.application.name=WebAntSwaggerToGherkin
server.port=8082
spring.datasource.url=${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:test_platform}}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:swagger_to_gherkin}
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.default-schema=${DB_SCHEMA:swagger_to_gherkin}
spring.flyway.schemas=${DB_SCHEMA:swagger_to_gherkin}
app.storage.root=${APP_STORAGE_ROOT:temp/storage}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:9000/application/o/test-platform/jwks/}
logging.level.root=INFO
logging.level.webant.swaggertogherkin=DEBUG
logging.level.org.springframework.web=DEBUG